version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    command: sh -c "streamlit run app.py --server.address 0.0.0.0 --server.port 8501"
    restart: unless-stopped
